version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: beehive
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # <-- добавить эту строку
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: beehive
    depends_on:
      - db

volumes:
  pgdata: